// ============================================================
// Character image compressor
// Reads source images, produces small JPEGs as base64 data URIs,
// and writes them to src/js/00-assets.js (CHARACTER_ASSETS).
// Run: node tools/compress-images.js
// ============================================================
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'js', '00-assets.js');
const IMG_DIR = 'images-src';

const AVATAR_SIZE = 256;   // square, centre-cropped
const BG_SIZE = 1280;      // max dimension, contained
const JPEG_Q = 82;

// charId -> source filename (relative to project root)
const SOURCES = [
  { id: 'c_rem',       file: 'rem.jpg' },
  { id: 'c_ram',       file: 'ram.png' },
  { id: 'c_twins',     file: 'rem_ram__4k__by_keep_m_dckcq0a.png' },
  { id: 'c_sparxie',   file: 'spark.png' },
  { id: 'c_yuki_high', file: 'yuki123456.png' },
];

async function makeAvatar(src) {
  return sharp(src)
    .rotate()                                             // auto-orient from EXIF
    .resize(AVATAR_SIZE, AVATAR_SIZE, { fit: 'cover', position: 'centre' })
    .flatten({ background: '#ffffff' })
    .jpeg({ quality: JPEG_Q })
    .toBuffer();
}

async function makeBg(src) {
  return sharp(src)
    .rotate()
    .resize(BG_SIZE, BG_SIZE, { fit: 'inside', withoutEnlargement: true })
    .flatten({ background: '#ffffff' })
    .jpeg({ quality: JPEG_Q })
    .toBuffer();
}

const toURI = buf => 'data:image/jpeg;base64,' + buf.toString('base64');

async function main() {
  const assets = {};
  let total = 0;
  for (const s of SOURCES) {
    const p = path.join(ROOT, IMG_DIR, s.file);
    if (!fs.existsSync(p)) { console.error('MISSING: ' + p); process.exit(1); }
    const avatar = await makeAvatar(p);
    const bg = await makeBg(p);
    assets[s.id] = { avatar: toURI(avatar), bg: toURI(bg) };
    total += avatar.length + bg.length;
    console.log(s.id.padEnd(12) + ' avatar ' + (avatar.length / 1024).toFixed(0).padStart(4) + 'KB  bg ' + (bg.length / 1024).toFixed(0).padStart(4) + 'KB');
  }
  const header = '// ============================================================\n' +
    '// CHARACTER IMAGE ASSETS (auto-generated by tools/compress-images.js)\n' +
    '// avatar: 256px square JPEG · bg: ≤1280px JPEG · base64 data URIs\n' +
    '// ============================================================\n';
  const body = 'const CHARACTER_ASSETS = ' + JSON.stringify(assets, null, 2) + ';\n';
  fs.writeFileSync(OUT, header + body, 'utf8');
  console.log('Wrote ' + OUT + ' (images total ' + (total / 1024).toFixed(0) + ' KB)');
}

main().catch(e => { console.error(e); process.exit(1); });
